# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSBM2D045qOsX3m_Wy0W5Dk9kdYlhXvX
"""

import hashlib
import time

def hash_data(data):
    return hashlib.sha256(str(data).encode()).hexdigest()

SHARED_KEY = "SHARED_SECRET_KEY"

def encrypt(data, key):
    return f"{data}::ENCRYPTED_WITH::{key}"

def decrypt(encrypted_data, key):
    if key in encrypted_data:
        return encrypted_data.split("::ENCRYPTED_WITH::")[0]
    return None

class User:
    def __init__(self, name):
        self.name = name
        self.public_key = f"{name}_PUBLIC_KEY"
        self.private_key = f"{name}_PRIVATE_KEY"

A = User("A")
B = User("B")
C = User("C")
D = User("D")

class Block:
    def __init__(self, index, prev_hash, data_hash, owner, access_list):
        self.index = index
        self.prev_hash = prev_hash
        self.data_hash = data_hash
        self.owner = owner
        self.access_list = access_list
        self.timestamp = time.time()

    def block_hash(self):
        content = (
            str(self.index) +
            self.prev_hash +
            self.data_hash +
            self.owner +
            str(self.access_list) +
            str(self.timestamp)
        )
        return hash_data(content)

BLOCKCHAIN = []

genesis = Block(
    index=0,
    prev_hash="0",
    data_hash="GENESIS",
    owner=A.public_key,
    access_list=[]
)

BLOCKCHAIN.append(genesis)

P2P_STORAGE = {}

video_data = "VIDEO_FILE_DATA"

encrypted_video = encrypt(video_data, SHARED_KEY)
data_hash = hash_data(encrypted_video)

P2P_STORAGE[data_hash] = encrypted_video

encrypted_video = encrypt(video_data, SHARED_KEY)

data_hash = hash_data(encrypted_video)

P2P_STORAGE[data_hash] = encrypted_video

access_list = {
    B.public_key,
    C.public_key
}

prev_block = BLOCKCHAIN[-1]

new_block = Block(
    index=prev_block.index + 1,
    prev_hash=prev_block.block_hash(),
    data_hash=data_hash,
    owner=B.public_key,
    access_list=access_list
)

BLOCKCHAIN.append(new_block)

def request_data(user, block):
    if user.public_key in block.access_list:
        encrypted = P2P_STORAGE[block.data_hash]
        decrypted = decrypt(encrypted, SHARED_KEY)
        print(f"{user.name}: ACCESS GRANTED →", decrypted)
    else:
        print(f"{user.name}: ACCESS DENIED")

request_data(A, new_block)
request_data(B, new_block)
request_data(C, new_block)
request_data(D, new_block)